# Generated by Django 4.0.4 on 2022-05-16 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_kakao_id_user_kakao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='kakao',
            new_name='kakao_id',
        ),
    ]
