# Generated by Django 4.0.4 on 2022-05-16 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='petsitter_id',
            new_name='petsitter',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='reviewimage',
            old_name='review_id',
            new_name='review',
        ),
    ]
