# Generated by Django 4.0.4 on 2022-05-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsitters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petsitter',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
