# Generated by Django 4.0.4 on 2022-05-11 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petsitters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petsitterimage',
            old_name='Petsitter_id',
            new_name='petsitter_id',
        ),
    ]
