# Generated by Django 4.0.4 on 2022-05-16 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petsitters', '0002_rename_petsitter_id_petsitterimage_petsitter_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='petsitter_id',
            new_name='petsitterv',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='petsitterimage',
            old_name='petsitter_id',
            new_name='petsitter',
        ),
        migrations.RenameField(
            model_name='petsittertype',
            old_name='petsitter_id',
            new_name='petsitter',
        ),
        migrations.RenameField(
            model_name='petsittertype',
            old_name='type_id',
            new_name='type',
        ),
    ]
