# Generated by Django 4.0.4 on 2022-05-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsitters', '0003_rename_petsitter_id_comment_petsitterv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petsitter',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
