# Generated by Django 4.0.4 on 2022-05-16 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petsitters', '0004_petsitter_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='petsitterv',
            new_name='petsitter',
        ),
    ]
