# Generated by Django 4.0.4 on 2022-05-16 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petsitters', '0005_rename_petsitterv_comment_petsitter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petsitter',
            old_name='types',
            new_name='type',
        ),
    ]
